import type { PermissionKey, PermissionScope } from './permissions.js';
import type { RoleKey } from './roles.js';

// Seed values for the role→permission matrix, spec §5.4. Mechanically
// derived from the §5.4 table in spec.md (parsed directly from the file,
// not retyped by hand, to eliminate transcription error on a 14-role by
// 35-row grid) plus a documented set of additions for permission keys that
// have no dedicated matrix row (see below).
//
// Two deliberate departures from a literal reading of the table:
//
// 1. OWNER and 👁 on a write-shaped row. The table marks OWNER 👁 on "cash
//    verify" and "shift manage", both mutating actions. Taken literally
//    that would grant OWNER the actual cash:verify/shift:manage
//    permissions — but spec §5.4 states explicitly: "OWNER is read-only
//    across the entire system except payment:verify and report:export...
//    Enforce this at the API layer." The prose rule is authoritative:
//    OWNER does NOT get cash:verify or shift:manage. The same "👁 on a
//    write row = no grant" reading is applied to "fnb update_status" for
//    RESORT_MANAGER/ADMIN_HEAD/ADMIN_STAFF/CASHIER (all 👁 there) for
//    consistency with the legend's own definition of 👁 as "read-only
//    variant" — those roles can see the kitchen board (fnb:read, granted
//    via the "fnb create order" row) but don't drag tickets through it;
//    that's Restaurant Manager/Staff's job (✅ on that row).
//
// 2. Permission keys with no matrix row at all: workorder:read (distinct
//    from workorder:read_all in §5.3's key list — granted to every role,
//    since everyone can create a ticket and "My tasks" views need to read
//    at least your own), payment:read/cash:read/inventory:read (granted
//    to whichever roles already hold the corresponding submit/verify/
//    record/adjust/request permission — you need to see the queue to act
//    on it), shift:read (granted to every role — everyone needs to see
//    their own roster even though only a subset can edit it),
//    amenity:read/amenity:approve/amenity:manage, fnb:read,
//    inspection:submit/inspection:read, incident:read, restday:request,
//    system:configure. Each is a reasoned inference consistent with the
//    matrix's other patterns, not an arbitrary default — see the
//    scaffold-generation script referenced in the M1 commit for the exact
//    per-key reasoning if this ever needs revisiting.
export const ROLE_PERMISSIONS: Record<RoleKey, Partial<Record<PermissionKey, PermissionScope>>> = {
  SYSTEM_ADMIN: {
    'amenity:approve': 'ALL',
    'amenity:issue': 'ALL',
    'amenity:manage': 'ALL',
    'amenity:read': 'ALL',
    'amenity:request': 'ALL',
    'amenity:return': 'ALL',
    'audit:read': 'ALL',
    'booking:checkin': 'ALL',
    'booking:checkout': 'ALL',
    'booking:create': 'ALL',
    'booking:read': 'ALL',
    'booking:update': 'ALL',
    'cash:read': 'ALL',
    'cash:record': 'ALL',
    'cash:verify': 'ALL',
    'fnb:create': 'ALL',
    'fnb:manage_menu': 'ALL',
    'fnb:read': 'ALL',
    'fnb:update_status': 'ALL',
    'folio:charge': 'ALL',
    'folio:read': 'ALL',
    'folio:settle': 'ALL',
    'folio:void': 'ALL',
    'incident:create': 'ALL',
    'incident:read': 'ALL',
    'inspection:read': 'ALL',
    'inspection:submit': 'ALL',
    'inventory:adjust': 'ALL',
    'inventory:read': 'ALL',
    'inventory:request': 'ALL',
    'payment:read': 'ALL',
    'payment:submit': 'ALL',
    'payment:verify': 'ALL',
    'report:export': 'ALL',
    'report:view': 'ALL',
    'restday:approve': 'ALL',
    'restday:request': 'ALL',
    'role:manage': 'ALL',
    'shift:manage': 'ALL',
    'shift:read': 'ALL',
    'system:configure': 'ALL',
    'unit:block': 'ALL',
    'unit:manage': 'ALL',
    'unit:read': 'ALL',
    'unit:update_status': 'ALL',
    'unittype:manage': 'ALL',
    'user:manage': 'ALL',
    'user:read': 'ALL',
    'workorder:assign': 'ALL',
    'workorder:close': 'ALL',
    'workorder:create': 'ALL',
    'workorder:read': 'ALL',
    'workorder:read_all': 'ALL',
    'workorder:update_status': 'ALL',
    'workorder:verify': 'ALL',
  },
  OWNER: {
    'audit:read': 'ALL',
    'booking:read': 'ALL',
    'cash:read': 'ALL',
    'folio:read': 'ALL',
    'incident:read': 'ALL',
    'payment:read': 'ALL',
    'payment:verify': 'ALL',
    'report:export': 'ALL',
    'report:view': 'ALL',
    'shift:read': 'ALL',
    'unit:read': 'ALL',
    'workorder:read': 'ALL',
    'workorder:read_all': 'ALL',
  },
  RESORT_MANAGER: {
    'amenity:approve': 'ALL',
    'amenity:issue': 'ALL',
    'amenity:manage': 'ALL',
    'amenity:read': 'ALL',
    'amenity:request': 'ALL',
    'amenity:return': 'ALL',
    'audit:read': 'ALL',
    'booking:checkin': 'ALL',
    'booking:checkout': 'ALL',
    'booking:create': 'ALL',
    'booking:read': 'ALL',
    'booking:update': 'ALL',
    'cash:read': 'ALL',
    'cash:record': 'ALL',
    'cash:verify': 'ALL',
    'fnb:create': 'ALL',
    'fnb:manage_menu': 'ALL',
    'fnb:read': 'ALL',
    'folio:charge': 'ALL',
    'folio:read': 'ALL',
    'folio:settle': 'ALL',
    'folio:void': 'ALL',
    'incident:create': 'ALL',
    'incident:read': 'ALL',
    'inspection:read': 'ALL',
    'inspection:submit': 'ALL',
    'inventory:adjust': 'ALL',
    'inventory:read': 'ALL',
    'inventory:request': 'ALL',
    'payment:read': 'ALL',
    'payment:submit': 'ALL',
    'payment:verify': 'ALL',
    'report:export': 'ALL',
    'report:view': 'ALL',
    'restday:approve': 'ALL',
    'restday:request': 'ALL',
    'shift:manage': 'ALL',
    'shift:read': 'ALL',
    'unit:block': 'ALL',
    'unit:manage': 'ALL',
    'unit:read': 'ALL',
    'unit:update_status': 'ALL',
    'unittype:manage': 'ALL',
    'user:read': 'ALL',
    'workorder:assign': 'ALL',
    'workorder:close': 'ALL',
    'workorder:create': 'ALL',
    'workorder:read': 'ALL',
    'workorder:read_all': 'ALL',
    'workorder:update_status': 'ALL',
    'workorder:verify': 'ALL',
  },
  OPS_SAFETY_SUPERVISOR: {
    'amenity:approve': 'ALL',
    'amenity:issue': 'ALL',
    'amenity:read': 'ALL',
    'amenity:request': 'ALL',
    'amenity:return': 'ALL',
    'booking:checkin': 'ALL',
    'booking:checkout': 'ALL',
    'booking:read': 'ALL',
    'cash:read': 'ALL',
    'cash:record': 'ALL',
    'cash:verify': 'ALL',
    'folio:read': 'ALL',
    'folio:void': 'ALL',
    'incident:create': 'ALL',
    'incident:read': 'ALL',
    'inspection:read': 'ALL',
    'inspection:submit': 'ALL',
    'inventory:adjust': 'ALL',
    'inventory:read': 'ALL',
    'inventory:request': 'ALL',
    'report:export': 'ALL',
    'report:view': 'ALL',
    'restday:approve': 'ALL',
    'restday:request': 'ALL',
    'shift:manage': 'ALL',
    'shift:read': 'ALL',
    'unit:block': 'ALL',
    'unit:read': 'ALL',
    'unit:update_status': 'ALL',
    'workorder:assign': 'ALL',
    'workorder:close': 'ALL',
    'workorder:create': 'ALL',
    'workorder:read': 'ALL',
    'workorder:read_all': 'ALL',
    'workorder:update_status': 'ALL',
    'workorder:verify': 'ALL',
  },
  ADMIN_HEAD: {
    'amenity:approve': 'ALL',
    'amenity:issue': 'ALL',
    'amenity:read': 'ALL',
    'amenity:request': 'ALL',
    'amenity:return': 'ALL',
    'booking:checkin': 'ALL',
    'booking:checkout': 'ALL',
    'booking:create': 'ALL',
    'booking:read': 'ALL',
    'booking:update': 'ALL',
    'cash:read': 'ALL',
    'cash:record': 'ALL',
    'fnb:create': 'ALL',
    'fnb:read': 'ALL',
    'folio:charge': 'ALL',
    'folio:read': 'ALL',
    'folio:settle': 'ALL',
    'incident:create': 'ALL',
    'incident:read': 'ALL',
    'inventory:read': 'ALL',
    'inventory:request': 'ALL',
    'payment:read': 'ALL',
    'payment:submit': 'ALL',
    'payment:verify': 'ALL',
    'report:export': 'ALL',
    'report:view': 'ALL',
    'restday:request': 'ALL',
    'shift:manage': 'ALL',
    'shift:read': 'ALL',
    'unit:read': 'ALL',
    'unit:update_status': 'ALL',
    'workorder:create': 'ALL',
    'workorder:read': 'ALL',
    'workorder:read_all': 'ALL',
    'workorder:update_status': 'ALL',
  },
  ADMIN_STAFF: {
    'amenity:approve': 'ALL',
    'amenity:issue': 'ALL',
    'amenity:read': 'ALL',
    'amenity:request': 'ALL',
    'amenity:return': 'ALL',
    'booking:checkin': 'ALL',
    'booking:checkout': 'ALL',
    'booking:create': 'ALL',
    'booking:read': 'ALL',
    'booking:update': 'ALL',
    'fnb:create': 'ALL',
    'fnb:read': 'ALL',
    'folio:charge': 'ALL',
    'folio:read': 'ALL',
    'incident:create': 'ALL',
    'payment:read': 'ALL',
    'payment:submit': 'ALL',
    'restday:request': 'ALL',
    'shift:read': 'ALL',
    'unit:read': 'ALL',
    'unit:update_status': 'ALL',
    'workorder:create': 'ALL',
    'workorder:read': 'ALL',
    'workorder:update_status': 'ALL',
  },
  CASHIER: {
    'amenity:approve': 'ALL',
    'amenity:issue': 'ALL',
    'amenity:read': 'ALL',
    'amenity:request': 'ALL',
    'amenity:return': 'ALL',
    'booking:checkin': 'ALL',
    'booking:checkout': 'ALL',
    'booking:create': 'ALL',
    'booking:read': 'ALL',
    'booking:update': 'ALL',
    'cash:read': 'ALL',
    'cash:record': 'ALL',
    'fnb:create': 'ALL',
    'fnb:read': 'ALL',
    'folio:charge': 'ALL',
    'folio:read': 'ALL',
    'folio:settle': 'ALL',
    'incident:create': 'ALL',
    'payment:read': 'ALL',
    'payment:submit': 'ALL',
    'report:view': 'ALL',
    'restday:request': 'ALL',
    'shift:read': 'ALL',
    'unit:read': 'ALL',
    'workorder:create': 'ALL',
    'workorder:read': 'ALL',
  },
  POC_HOUSEKEEPING: {
    'amenity:approve': 'ALL',
    'amenity:issue': 'ALL',
    'amenity:read': 'ALL',
    'amenity:request': 'ALL',
    'amenity:return': 'ALL',
    'booking:read': 'ALL',
    'incident:create': 'ALL',
    'inspection:read': 'ALL',
    'inspection:submit': 'ALL',
    'inventory:adjust': 'ALL',
    'inventory:read': 'ALL',
    'inventory:request': 'ALL',
    'report:view': 'DEPARTMENT',
    'restday:request': 'ALL',
    'shift:manage': 'ALL',
    'shift:read': 'ALL',
    'unit:block': 'ALL',
    'unit:read': 'ALL',
    'unit:update_status': 'ALL',
    'workorder:assign': 'ALL',
    'workorder:close': 'ALL',
    'workorder:create': 'ALL',
    'workorder:read': 'ALL',
    'workorder:read_all': 'DEPARTMENT',
    'workorder:update_status': 'ALL',
    'workorder:verify': 'ALL',
  },
  HOUSEKEEPING_STAFF: {
    'amenity:approve': 'ALL',
    'amenity:issue': 'ALL',
    'amenity:read': 'ALL',
    'amenity:return': 'ALL',
    'incident:create': 'ALL',
    'restday:request': 'ALL',
    'shift:read': 'ALL',
    'unit:read': 'ALL',
    'unit:update_status': 'ALL',
    'workorder:create': 'ALL',
    'workorder:read': 'ALL',
    'workorder:update_status': 'ALL',
  },
  POC_MAINTENANCE: {
    'incident:create': 'ALL',
    'inspection:read': 'ALL',
    'inspection:submit': 'ALL',
    'inventory:adjust': 'ALL',
    'inventory:read': 'ALL',
    'inventory:request': 'ALL',
    'report:view': 'DEPARTMENT',
    'restday:request': 'ALL',
    'shift:manage': 'ALL',
    'shift:read': 'ALL',
    'unit:block': 'ALL',
    'unit:read': 'ALL',
    'unit:update_status': 'ALL',
    'workorder:assign': 'ALL',
    'workorder:close': 'ALL',
    'workorder:create': 'ALL',
    'workorder:read': 'ALL',
    'workorder:read_all': 'DEPARTMENT',
    'workorder:update_status': 'ALL',
    'workorder:verify': 'ALL',
  },
  MAINTENANCE_STAFF: {
    'incident:create': 'ALL',
    'restday:request': 'ALL',
    'shift:read': 'ALL',
    'unit:read': 'ALL',
    'unit:update_status': 'ALL',
    'workorder:create': 'ALL',
    'workorder:read': 'ALL',
    'workorder:update_status': 'ALL',
  },
  RESORT_STAFF: {
    'amenity:approve': 'ALL',
    'amenity:issue': 'ALL',
    'amenity:read': 'ALL',
    'amenity:request': 'ALL',
    'amenity:return': 'ALL',
    'incident:create': 'ALL',
    'restday:request': 'ALL',
    'shift:read': 'ALL',
    'unit:read': 'ALL',
    'workorder:create': 'ALL',
    'workorder:read': 'ALL',
    'workorder:update_status': 'ALL',
  },
  RESTAURANT_MANAGER: {
    'booking:read': 'ALL',
    'cash:read': 'ALL',
    'cash:record': 'ALL',
    'fnb:create': 'ALL',
    'fnb:manage_menu': 'ALL',
    'fnb:read': 'ALL',
    'fnb:update_status': 'ALL',
    'folio:charge': 'ALL',
    'folio:read': 'ALL',
    'incident:create': 'ALL',
    'inventory:adjust': 'ALL',
    'inventory:read': 'ALL',
    'inventory:request': 'ALL',
    'report:export': 'ALL',
    'report:view': 'DEPARTMENT',
    'restday:request': 'ALL',
    'shift:manage': 'ALL',
    'shift:read': 'ALL',
    'unit:read': 'ALL',
    'workorder:assign': 'ALL',
    'workorder:close': 'ALL',
    'workorder:create': 'ALL',
    'workorder:read': 'ALL',
    'workorder:read_all': 'DEPARTMENT',
    'workorder:update_status': 'ALL',
    'workorder:verify': 'ALL',
  },
  RESTAURANT_STAFF: {
    'fnb:create': 'ALL',
    'fnb:read': 'ALL',
    'fnb:update_status': 'ALL',
    'folio:charge': 'ALL',
    'incident:create': 'ALL',
    'inventory:read': 'ALL',
    'inventory:request': 'ALL',
    'restday:request': 'ALL',
    'shift:read': 'ALL',
    'workorder:create': 'ALL',
    'workorder:read': 'ALL',
    'workorder:update_status': 'ALL',
  },
};

